services:
  postgres:
    image: postgres:13
    env_file:
      - stack.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - invoicer-db
      - node-server

  invoice-app:
    build: .
    depends_on:
      - postgres
    env_file:
      - stack.env
    volumes:
      - ./invoices:/app/invoices
    networks:
      - invoicer-db
      - node-server

volumes:
  postgres_data:

networks:
  invoicer-db:
  node-server:
